level-type=minecraft\:flat
gamemode=creative
online-mode=false
spawn-protection=16
difficulty=peaceful
spawn-monsters=false
generate-structures=false
level-seed=4337
server-ip=127.0.0.1
enable-query=false
enable-rcon=false
